In [12]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') 
import statistics as stats

In [13]:
temperatures= pd.read_csv("/Users/lcorrea/Documents/GitHub/proyecto ETL/Environment_Temperature.csv",sep=',', encoding='latin-1')

In [14]:
temperatures

,Area Code,Area,Months Code,Months,Element Code,Element,Unit,Y1961,Y1962,Y1963,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,2,Afghanistan,7001,January,7271,Temperature change,°C,0.777,0.062,2.744,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,2,Afghanistan,7001,January,6078,Standard Deviation,°C,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,2,Afghanistan,7002,February,7271,Temperature change,°C,-1.743,2.465,3.919,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,2,Afghanistan,7002,February,6078,Standard Deviation,°C,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,2,Afghanistan,7003,March,7271,Temperature change,°C,0.516,1.336,0.403,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9651,5873,OECD,7018,JunJulAug,6078,Standard Deviation,°C,0.247,0.247,0.247,...,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247
9652,5873,OECD,7019,SepOctNov,7271,Temperature change,°C,0.036,0.461,0.665,...,0.958,1.106,0.885,1.041,0.999,1.670,1.535,1.194,0.581,1.233
9653,5873,OECD,7019,SepOctNov,6078,Standard Deviation,°C,0.378,0.378,0.378,...,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378
9654,5873,OECD,7020,Meteorological year,7271,Temperature change,°C,0.165,-0.009,0.134,...,1.246,0.805,1.274,0.991,0.811,1.282,1.850,1.349,1.088,1.297
9655,5873,OECD,7020,Meteorological year,6078,Standard Deviation,°C,0.260,0.260,0.260,...,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260

In [16]:

temperatures.drop(['Area Code', 'Months Code','Months'], axis=1, inplace = True)

In [17]:
temperatures

,Area,Element Code,Element,Unit,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,7271,Temperature change,°C,0.777,0.062,2.744,-5.232,1.868,3.629,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
1,Afghanistan,6078,Standard Deviation,°C,1.950,1.950,1.950,1.950,1.950,1.950,...,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950,1.950
2,Afghanistan,7271,Temperature change,°C,-1.743,2.465,3.919,-0.202,-0.096,3.397,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
3,Afghanistan,6078,Standard Deviation,°C,2.597,2.597,2.597,2.597,2.597,2.597,...,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597,2.597
4,Afghanistan,7271,Temperature change,°C,0.516,1.336,0.403,1.659,-0.909,-0.069,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9651,OECD,6078,Standard Deviation,°C,0.247,0.247,0.247,0.247,0.247,0.247,...,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247,0.247
9652,OECD,7271,Temperature change,°C,0.036,0.461,0.665,-0.157,-0.203,-0.295,...,0.958,1.106,0.885,1.041,0.999,1.670,1.535,1.194,0.581,1.233
9653,OECD,6078,Standard Deviation,°C,0.378,0.378,0.378,0.378,0.378,0.378,...,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378,0.378
9654,OECD,7271,Temperature change,°C,0.165,-0.009,0.134,-0.190,-0.385,-0.166,...,1.246,0.805,1.274,0.991,0.811,1.282,1.850,1.349,1.088,1.297
9655,OECD,6078,Standard Deviation,°C,0.260,0.260,0.260,0.260,0.260,0.260,...,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260,0.260

In [18]:
temperatures.drop(temperatures[(temperatures['Area'] == 'OECD')].index, inplace=True)

In [19]:
temperatures.drop(temperatures[(temperatures['Area'] == 'Non-Annex I countries')].index, inplace=True)

temperatures.drop(temperatures[(temperatures['Area'] == 'Annex I countries')].index, inplace=True)

temperatures.drop(temperatures[(temperatures['Area'] == 'Net Food Importing Developing Countries')].index, inplace=True)

temperatures.drop(temperatures[(temperatures['Area'] == 'Low Income Food Deficit Countries')].index, inplace=True)

temperatures.drop(temperatures[(temperatures['Area'] == 'Small Island Developing States')].index, inplace=True)


temperatures.drop(temperatures[(temperatures['Area'] == 'Land Locked Developing Countries')].index, inplace=True)

temperatures.drop(temperatures[(temperatures['Area'] == 'Least Developed Countries')].index, inplace=True)

In [56]:
temperatures.drop(temperatures[(temperatures['Area'] == 'European Union')].index, inplace=True)

In [20]:
temperatures.drop(temperatures[(temperatures['Element'] == 'Standard Deviation')].index, inplace=True)

In [21]:
temperatures

,Area,Element Code,Element,Unit,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
0,Afghanistan,7271,Temperature change,°C,0.777,0.062,2.744,-5.232,1.868,3.629,...,3.601,1.179,-0.583,1.233,1.755,1.943,3.416,1.201,1.996,2.951
2,Afghanistan,7271,Temperature change,°C,-1.743,2.465,3.919,-0.202,-0.096,3.397,...,1.212,0.321,-3.201,1.494,-3.187,2.699,2.251,-0.323,2.705,0.086
4,Afghanistan,7271,Temperature change,°C,0.516,1.336,0.403,1.659,-0.909,-0.069,...,3.390,0.748,-0.527,2.246,-0.076,-0.497,2.296,0.834,4.418,0.234
6,Afghanistan,7271,Temperature change,°C,-1.709,0.117,0.919,-0.533,-1.816,-1.192,...,2.591,1.712,1.417,-0.052,0.585,1.589,0.980,1.252,1.442,0.899
8,Afghanistan,7271,Temperature change,°C,1.412,-0.092,-0.690,-0.160,-0.190,-0.192,...,1.419,3.643,0.909,1.201,0.959,1.862,3.246,3.280,0.855,0.647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9374,European Union,7271,Temperature change,°C,1.400,0.300,-3.256,-0.702,-0.398,-0.123,...,-0.666,-0.463,0.759,0.495,2.789,1.918,2.884,1.466,1.340,2.028
9376,European Union,7271,Temperature change,°C,1.430,-0.858,-0.112,0.173,-0.440,0.119,...,0.933,2.092,1.813,0.261,2.324,1.747,1.664,1.976,2.063,1.685
9378,European Union,7271,Temperature change,°C,0.101,-0.579,0.155,0.219,-0.620,-0.061,...,1.608,1.224,1.473,1.551,1.156,1.731,1.650,1.769,2.448,2.307
9380,European Union,7271,Temperature change,°C,1.225,0.174,0.908,0.181,-0.613,0.156,...,0.077,1.719,1.214,1.298,1.960,1.512,1.059,1.063,1.880,1.516
9382,European Union,7271,Temperature change,°C,1.039,-0.241,-0.576,-0.032,-0.518,0.022,...,0.488,1.143,1.315,0.901,2.057,1.727,1.814,1.569,1.933,1.884

In [22]:
temperatures.drop(['Element Code'], axis=1, inplace = True)

In [25]:
data_temp = temperatures.apply(lambda row: row[temperatures['Area'].isin(['Bangladesh','China','Vietnam','Pakistan','India','Myanmar'])])

In [26]:
data_temp

,Area,Element,Unit,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
578,Bangladesh,Temperature change,°C,0.928,-1.171,-0.318,-0.268,0.396,0.440,0.441,...,-0.580,-0.772,-0.795,-1.743,0.206,1.462,0.392,1.376,-0.415,1.019
580,Bangladesh,Temperature change,°C,-1.527,0.024,1.319,0.310,-0.417,1.338,0.601,...,0.836,0.563,-0.052,0.475,-0.119,1.088,2.727,1.877,1.827,1.264
582,Bangladesh,Temperature change,°C,1.024,0.060,-0.066,1.159,-1.184,0.290,-1.120,...,2.119,0.357,0.911,0.659,0.158,0.608,1.981,-0.318,1.659,0.427
584,Bangladesh,Temperature change,°C,0.813,0.345,-0.855,-0.567,-0.332,0.708,-1.135,...,1.474,-0.229,-0.476,0.187,1.412,-0.925,1.837,-0.009,-0.054,0.422
586,Bangladesh,Temperature change,°C,0.390,-0.233,-1.122,-0.383,0.351,1.072,0.083,...,0.531,-0.071,0.942,-0.278,1.337,0.803,0.448,1.340,-0.294,1.470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5634,Pakistan,Temperature change,°C,-0.606,0.105,0.828,-0.943,0.041,0.942,-0.276,...,1.254,0.096,-0.792,0.559,-0.280,0.777,1.164,1.545,1.433,0.320
5636,Pakistan,Temperature change,°C,-0.250,0.201,-0.464,0.764,-1.625,-0.645,-1.084,...,3.026,1.350,0.550,0.788,-0.158,0.642,1.627,1.865,2.231,0.222
5638,Pakistan,Temperature change,°C,0.078,-0.071,0.638,-0.160,-0.414,-0.105,0.009,...,-0.142,0.412,0.330,0.322,0.864,-0.134,0.429,0.216,0.737,0.525
5640,Pakistan,Temperature change,°C,-0.197,-1.175,0.698,-1.084,0.913,-0.741,0.152,...,0.610,1.076,0.342,1.178,0.852,0.660,1.232,1.005,0.714,0.823
5642,Pakistan,Temperature change,°C,-0.244,-0.235,0.425,-0.356,-0.271,-0.137,-0.300,...,1.187,0.734,0.108,0.712,0.320,0.486,1.113,1.158,1.279,0.473

In [38]:

data_temp.drop(['Y1961', 'Y1962','Y1963','Y1964', 'Y1965','Y1966','Y1967','Y1968', 'Y1969'], axis=1, inplace = True)

In [39]:
data_temp

,Area,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,...,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019
578,Bangladesh,Temperature change,°C,-0.335,0.095,0.517,0.638,-0.387,-0.145,-0.063,...,-0.580,-0.772,-0.795,-1.743,0.206,1.462,0.392,1.376,-0.415,1.019
580,Bangladesh,Temperature change,°C,0.041,-0.654,-2.095,1.214,-0.238,0.082,0.482,...,0.836,0.563,-0.052,0.475,-0.119,1.088,2.727,1.877,1.827,1.264
582,Bangladesh,Temperature change,°C,0.007,-0.603,-0.079,-0.576,-0.361,0.606,0.617,...,2.119,0.357,0.911,0.659,0.158,0.608,1.981,-0.318,1.659,0.427
584,Bangladesh,Temperature change,°C,0.203,-1.625,-0.643,0.965,-0.548,0.452,0.232,...,1.474,-0.229,-0.476,0.187,1.412,-0.925,1.837,-0.009,-0.054,0.422
586,Bangladesh,Temperature change,°C,0.579,-0.810,0.565,-0.975,-0.526,-0.124,-0.760,...,0.531,-0.071,0.942,-0.278,1.337,0.803,0.448,1.340,-0.294,1.470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5634,Pakistan,Temperature change,°C,0.804,-0.031,-0.967,-0.454,-1.340,-1.138,0.104,...,1.254,0.096,-0.792,0.559,-0.280,0.777,1.164,1.545,1.433,0.320
5636,Pakistan,Temperature change,°C,0.666,1.231,-0.515,0.591,0.992,-0.415,-0.759,...,3.026,1.350,0.550,0.788,-0.158,0.642,1.627,1.865,2.231,0.222
5638,Pakistan,Temperature change,°C,0.547,-0.004,-0.207,0.294,0.073,-0.449,-0.591,...,-0.142,0.412,0.330,0.322,0.864,-0.134,0.429,0.216,0.737,0.525
5640,Pakistan,Temperature change,°C,0.411,-0.266,-0.280,-0.083,-0.546,-0.379,0.012,...,0.610,1.076,0.342,1.178,0.852,0.660,1.232,1.005,0.714,0.823
5642,Pakistan,Temperature change,°C,0.607,0.233,-0.492,0.087,-0.205,-0.595,-0.308,...,1.187,0.734,0.108,0.712,0.320,0.486,1.113,1.158,1.279,0.473

In [40]:
data_temp.to_csv('temperatures.csv', index = False)